#!/usr/bin/env bash
# Made by Eduardo Echeverria, Hector Mantellini, Jesus Palencia
# Licence: GPL-2
LC_ALL=C

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: NO DEBES SER ROOT\e[00m"
	exit 1
fi

function pause() {
	read -p "$*"
}

case "$1" in
	instalar)
		sudo echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
		sudo apt -q update && apt -qy install gnupg wget gedit xclip zenity
		echo "Instalacion finalizada..."
		;;

	iniciar)
		echo -e "\e[00;31mScript para firmar el código de conducta de UBUNTU\e[00m"
		if ! [[ -f "$HOME"/UbuntuCodeofConduct-2.0.txt ]]; then
			echo "Descargando codigo de conducta"
			wget -q -O "$HOME"/UbuntuCodeofConduct-2.0.txt - https://launchpad.net/codeofconduct/2.0/+download
		fi
		echo "Generando llave"
		echo 'Key-Type: 1' > /tmp/genkey
		echo 'Key-Length: 2048' >> /tmp/genkey
		echo 'Subkey-Type: 1' >> /tmp/genkey
		echo 'Subkey-Length: 2048' >> /tmp/genkey
		echo 'Name-Real: $2 $3' >> /tmp/genkey
		echo 'Name-Email: $4' >> /tmp/genkey
		echo 'Expire-Date: 2y' >> /tmp/genkey
		script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
		millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
		rm -f /tmp/genkey
		rm -f /tmp/listo
		echo "Llave Generada"
		export GPGKEY=$millave
		gpg --send-keys --keyserver keyserver.ubuntu.com $millave
		echo "Se envio al keyserver de Ubuntu la siguiente llave: $millave"
		mihuella=$(gpg --fingerprint $millave | grep "Huella de clave" | cut -c 25-74)
		echo "$mihuella" | xclip -selection c
		
		echo "Su huella ya esta en el portapapeles. Siga las instrucciones a continuacion:"
		echo "1.- Abrir Launchpad.net en su navegador favorito"
		echo "2.- Pegar la huella digital que has copiado en la caja de texto Fingerprint,"
		echo "(use ctrl-v)"	
		echo "a continuación, haga clic en el botón Import Key. Launchpad,net utilizará la huella"
		echo "digital para comprobar su llave en el servidor de llaves de Ubuntu, y si tiene"
		echo "éxito, le sera enviado un correo electrónico."
		echo ""
		echo "3.- Una ves importada la llave revise su correo ya que launchpad.net le enviara un mensaje,"
		echo "haga click en el enlace que le indica dentro del correo, se encuentra luego del texto:"
		echo "Please go here to finish adding"
		echo "the key to your Launchpad account:"
		echo "4.- Al abrir el enlace se mostrara una pagina con una gran caja de texto"
		echo "solicitandote un texto firmado. Copie el texto de confirmacion que aparece"
		echo "en esa pagina el cual es algo similar a esto:"
		
		# hay que cambiar el mensaje 
		
		gpg --decrypt "$HOME"/correo.gpg > /tmp/descifrado
		decrypt=$(cat /tmp/descifrado | grep https | awk '{print $1}')
		firefox $decrypt
		
		echo "Please register 056439CD2486190A2C5A07390E6804DC16E7CB72 to the Launchpad user"
		echo "Matthew Revell. 2007-01-26 12:50 UTC pegalo en un editor de texto, coloque un"
		echo "nombre (ejemplo: confirmacion.txt) y guarde en su carpeta personal."

		pause "Presione Enter para continuar"


		read -p "Escriba nombre archivo:" ARCHIVO
		gpg --clearsign $ARCHIVO
		#while [ $? != 0 ]; do
		#	read -p "Escriba nombre archivo:" ARCHIVO
		#	gpg --clearsign $ARCHIVO
		#done
		pause "Presione Enter para continuar"

		#-------------

		echo "Firmado el archivo, fijate en tu carpeta personal aparece"
		echo "un nuevo archivo llamado con una terminacion *.asc, abrir con un editor de"
		echo "texto, copia y pega el contenido en la caja de texto de la pagina que abristes"
		echo "con el enlace que te llego por correo y dale Continue."
		echo "Ya con esto has agregado y confirmado tu llave GPG, ahora podemos pasar a firmar"
		echo "el codigo de conducta. Firmando el Codigo de Conducta lo primero que hiciste al"
		echo "comenzar con este script fue leer y descargar el Codigo De Conducta, por lo que"
		echo "procederemos a firmarlo."

		pause "Presione Enter para continuar"
		gpg --clearsign UbuntuCodeofConduct-2.0.txt

		echo "Generando llave SSH"
		ssh-keygen -b 1024 -t rsa -f "$HOME"/.ssh/id_rsa -N ''
		echo "LLave SSH generada"
		cat "$HOME"/.ssh/id_rsa.pub | xclip -selection c
		echo "ir a launchpan.net y utilizar ctrl + v para pegar la llave ssh en el campo correspondiente"
		;;

	*)
            	echo "USO: $(basename $0) {instalar|iniciar} nombre apellido tu@correo.com"
		;;

esac
exit 0
