#!/usr/bin/env bash
# Made by Eduardo Echeverria, Hector Mantellini, Jesus Palencia
# Licence: GPL-2
LC_ALL=C
minombre="UbuntuCodeofConduct-2.0.txt"

function pause() {
	read -p "$*"
}

case "$1" in
	instalar)
		clear
		if [[ "$EUID" != "0" ]]; then
			echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
			exit 1
		fi
		echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
		apt -q update
		apt -qy install gnupg wget gedit xclip beep
		echo "Instalacion finalizada..."
		;;

	iniciar)
		clear
		if [[ "$EUID" = "0" ]]; then
			echo -e "\e[00;31mERROR: NO DEBES SER ROOT\e[00m"
			exit 1
		fi
		if ! [[ -f /usr/bin/xclip ]]; then
			echo "Debe ejecutar la instalacion antes de continuar."
			exit 1
		fi
		rm -f /tmp/genkey
		rm -f /tmp/listo
		rm -f /tmp/descifrado
		rm -f "$HOME"/correo.gpg
		if ! [[ -f "$HOME"/"$minombre" ]]; then
			echo "Descargando codigo de conducta."
			wget -v -O "$HOME"/"$minombre" https://launchpad.net/codeofconduct/2.0/+download
			echo ""
			echo "Descarga finalizada."
		fi
		echo ""
		echo "Generando llave GPG"
		echo 'Key-Type: 1' > /tmp/genkey
		echo 'Key-Length: 2048' >> /tmp/genkey
		echo 'Subkey-Type: 1' >> /tmp/genkey
		echo 'Subkey-Length: 2048' >> /tmp/genkey
		echo 'Name-Real:' $2 $3 >> /tmp/genkey
		echo 'Name-Email:' $4 >> /tmp/genkey
		echo 'Expire-Date: 2y' >> /tmp/genkey
		script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
		millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
		rm -f /tmp/genkey
		rm -f /tmp/listo
		echo ""
		beep -r 3
		echo "Llave GPG Generada."
		export GPGKEY=$millave
		gpg --send-keys --keyserver keyserver.ubuntu.com $millave
		echo ""
		echo "Se envio al keyserver de Ubuntu la siguiente llave: $millave"
		mihuella=$(gpg --fingerprint $millave | grep "Huella de clave" | cut -c 25-74)
		echo "$mihuella" | xclip -selection c
		echo ""
		echo ""
		echo "Su huella esta almacenada temporalmente en el portapapeles."
		echo "Siga las instrucciones a continuacion:"
		echo ""
		echo "1.- Abrir Launchpad.net en su navegador favorito y loguearse"
		echo ""
		echo "2.- Ir a firmar codigo de conducta"
		echo ""
		echo "3.- Registrar su nueva llave, en el campo fingerprint pegue lo que esta en el portapapeles (ctrl + v)"
		echo "    presione el boton [Import Key]"
		echo ""
		echo "4.- Una vez realizada la accion anterior se le enviara un correo de confirmacion"
		echo ""
		echo "5.- Abra el correo que dice en el asunto: Launchpad: Confirm your OpenPGP Key"
		echo "    copie el texto en el bloque gpg y peguelo en el bloc de notas, luego guardelo en su directorio /home/SU_USUARIO con el nombre correo.gpg"
		echo ""
		echo "6.- Luego presione Enter en la pantalla de la consola, donde se ejecuta el script"
		echo "    se abrira una ventana del navegador por default donde hara clic en confirmar"
		echo ""
		echo "7.- Vaya de nuevo a firmar Codigo de Conducta y seleccione la opcion: 3 Sign it! (Firmar)"
		echo ""
		echo "8.- Pegue el contenido del portapapeles y presione continuar"
		echo ""
		pause "Presione Enter para continuar."
		gpg --decrypt "$HOME"/correo.gpg > /tmp/descifrado
		decrypt=$(cat /tmp/descifrado | grep https: | awk '{print $1}')
		firefox $decrypt
		pause "Presione Enter para continuar."
		echo ""
		echo "Se firmara el codigo de conducta."
		gpg --clearsign "$HOME"/"$minombre"
		echo ""
		echo "El codigo de conducta ha sido firmado."
		cat "$HOME"/"$minombre".asc | xclip -selection c
		rm -f /tmp/descifrado
		rm -f "$HOME"/correo.gpg
		echo ""
		echo "Vaya a launchpad.net y presione ctrl + v para pegar el contenido del codigo de conducta ya firmado."
		pause "Presione Enter para continuar."
		echo ""
		echo "Generando llave SSH"
		ssh-keygen -b 1024 -t rsa -f "$HOME"/.ssh/id_rsa -N ''
		echo ""
		echo "LLave SSH generada."
		cat "$HOME"/.ssh/id_rsa.pub | xclip -selection c
		echo ""
		echo "Su llave SSH  esta almacenada temporalmente en el portapapeles."
		echo ""
		echo "1.- Vaya a launchpad.net y haga clic en: ssh keys"
		echo ""
		echo "2.- Pegue (ctrl + v) el contenido del portapapeles y presione: importar public key"
		pause "Presione Enter para continuar."
		echo ""
		echo "Finalizado..."
		;;

	*)
            	echo "USO: $(basename $0) {instalar|iniciar} nombre apellido sudireccion@correo.com"
		;;

esac
exit 0
